### ISSUE TITLE
imagePullPolicy is set to Never

### ISSUE THREAD

**Issue by denisp13** [joaguas/aksdnsfallback#2]
Hey there , any reason why on dsfallback.yaml the imagePullPolicy is set to Never ?
It causing the pods triggered by the daemon set to be scheduled but the image will be not pulled

Fix
imagePullPolicy: Always

Cheers 
 Denis

**Comment by joaguas** [comment]
hi @denisp13 

If a node is affected and has no DNS servers configured, it will not be able to pull any images as it will fail to resolve the image registry's fqdn (docker,io, k8s.gcr.io, etc.)

The workarounds use a container image that AKS worker nodes already have in their container image cache (a collection of images used for AKS related components in order to improve deployment time) meaning it will need to pull it and will not need to resolve any DNS names.

If the image is not present or the pull policy is set to always it will not work
